[package]
name = "btmon"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
nom = "7.1.3"
serialport = "4.6.0"
time = "0.3.36"
probe-rs = { git = "https://github.com/probe-rs/probe-rs" }
