//! HCI command opcodes, event codes and LE subevent codes.
//!
//! Generated by `tools/gen_hci_ids.py` from the Bluetooth Core Specification
//! v6.3 (Vol 4, Part E). Do not edit by hand.

/// HCI command opcodes (`OGF << 10 | OCF`).
pub mod cmd {
    pub const INQUIRY: u16 = 0x0401;
    pub const INQUIRY_CANCEL: u16 = 0x0402;
    pub const PERIODIC_INQUIRY_MODE: u16 = 0x0403;
    pub const EXIT_PERIODIC_INQUIRY_MODE: u16 = 0x0404;
    pub const CREATE_CONNECTION: u16 = 0x0405;
    pub const DISCONNECT: u16 = 0x0406;
    pub const ADD_SCO_CONNECTION: u16 = 0x0407;
    pub const CREATE_CONNECTION_CANCEL: u16 = 0x0408;
    pub const ACCEPT_CONNECTION_REQUEST: u16 = 0x0409;
    pub const REJECT_CONNECTION_REQUEST: u16 = 0x040a;
    pub const LINK_KEY_REQUEST_REPLY: u16 = 0x040b;
    pub const LINK_KEY_REQUEST_NEGATIVE_REPLY: u16 = 0x040c;
    pub const PIN_CODE_REQUEST_REPLY: u16 = 0x040d;
    pub const PIN_CODE_REQUEST_NEGATIVE_REPLY: u16 = 0x040e;
    pub const CHANGE_CONNECTION_PACKET_TYPE: u16 = 0x040f;
    pub const AUTHENTICATION_REQUESTED: u16 = 0x0411;
    pub const SET_CONNECTION_ENCRYPTION: u16 = 0x0413;
    pub const CHANGE_CONNECTION_LINK_KEY: u16 = 0x0415;
    pub const LINK_KEY_SELECTION: u16 = 0x0417;
    pub const REMOTE_NAME_REQUEST: u16 = 0x0419;
    pub const REMOTE_NAME_REQUEST_CANCEL: u16 = 0x041a;
    pub const READ_REMOTE_SUPPORTED_FEATURES: u16 = 0x041b;
    pub const READ_REMOTE_EXTENDED_FEATURES: u16 = 0x041c;
    pub const READ_REMOTE_VERSION_INFORMATION: u16 = 0x041d;
    pub const READ_CLOCK_OFFSET: u16 = 0x041f;
    pub const READ_LMP_HANDLE: u16 = 0x0420;
    pub const SETUP_SYNCHRONOUS_CONNECTION: u16 = 0x0428;
    pub const ACCEPT_SYNCHRONOUS_CONNECTION_REQUEST: u16 = 0x0429;
    pub const REJECT_SYNCHRONOUS_CONNECTION_REQUEST: u16 = 0x042a;
    pub const IO_CAPABILITY_REQUEST_REPLY: u16 = 0x042b;
    pub const USER_CONFIRMATION_REQUEST_REPLY: u16 = 0x042c;
    pub const USER_CONFIRMATION_REQUEST_NEGATIVE_REPLY: u16 = 0x042d;
    pub const USER_PASSKEY_REQUEST_REPLY: u16 = 0x042e;
    pub const USER_PASSKEY_REQUEST_NEGATIVE_REPLY: u16 = 0x042f;
    pub const REMOTE_OOB_DATA_REQUEST_REPLY: u16 = 0x0430;
    pub const REMOTE_OOB_DATA_REQUEST_NEGATIVE_REPLY: u16 = 0x0433;
    pub const IO_CAPABILITY_REQUEST_NEGATIVE_REPLY: u16 = 0x0434;
    pub const CREATE_PHYSICAL_LINK: u16 = 0x0435;
    pub const ACCEPT_PHYSICAL_LINK: u16 = 0x0436;
    pub const DISCONNECT_PHYSICAL_LINK: u16 = 0x0437;
    pub const CREATE_LOGICAL_LINK: u16 = 0x0438;
    pub const ACCEPT_LOGICAL_LINK: u16 = 0x0439;
    pub const DISCONNECT_LOGICAL_LINK: u16 = 0x043a;
    pub const LOGICAL_LINK_CANCEL: u16 = 0x043b;
    pub const FLOW_SPEC_MODIFY: u16 = 0x043c;
    pub const ENHANCED_SETUP_SYNCHRONOUS_CONNECTION: u16 = 0x043d;
    pub const ENHANCED_ACCEPT_SYNCHRONOUS_CONNECTION_REQUEST: u16 = 0x043e;
    pub const TRUNCATED_PAGE: u16 = 0x043f;
    pub const TRUNCATED_PAGE_CANCEL: u16 = 0x0440;
    pub const SET_CONNECTIONLESS_PERIPHERAL_BROADCAST: u16 = 0x0441;
    pub const SET_CONNECTIONLESS_PERIPHERAL_BROADCAST_RECEIVE: u16 = 0x0442;
    pub const START_SYNCHRONIZATION_TRAIN: u16 = 0x0443;
    pub const RECEIVE_SYNCHRONIZATION_TRAIN: u16 = 0x0444;
    pub const REMOTE_OOB_EXTENDED_DATA_REQUEST_REPLY: u16 = 0x0445;
    pub const HOLD_MODE: u16 = 0x0801;
    pub const SNIFF_MODE: u16 = 0x0803;
    pub const EXIT_SNIFF_MODE: u16 = 0x0804;
    pub const PARK_STATE: u16 = 0x0805;
    pub const EXIT_PARK_STATE: u16 = 0x0806;
    pub const QOS_SETUP: u16 = 0x0807;
    pub const ROLE_DISCOVERY: u16 = 0x0809;
    pub const SWITCH_ROLE: u16 = 0x080b;
    pub const READ_LINK_POLICY_SETTINGS: u16 = 0x080c;
    pub const WRITE_LINK_POLICY_SETTINGS: u16 = 0x080d;
    pub const READ_DEFAULT_LINK_POLICY_SETTINGS: u16 = 0x080e;
    pub const WRITE_DEFAULT_LINK_POLICY_SETTINGS: u16 = 0x080f;
    pub const FLOW_SPECIFICATION: u16 = 0x0810;
    pub const SNIFF_SUBRATING: u16 = 0x0811;
    pub const SET_EVENT_MASK: u16 = 0x0c01;
    pub const RESET: u16 = 0x0c03;
    pub const SET_EVENT_FILTER: u16 = 0x0c05;
    pub const FLUSH: u16 = 0x0c08;
    pub const READ_PIN_TYPE: u16 = 0x0c09;
    pub const WRITE_PIN_TYPE: u16 = 0x0c0a;
    pub const CREATE_NEW_UNIT_KEY: u16 = 0x0c0b;
    pub const READ_STORED_LINK_KEY: u16 = 0x0c0d;
    pub const WRITE_STORED_LINK_KEY: u16 = 0x0c11;
    pub const DELETE_STORED_LINK_KEY: u16 = 0x0c12;
    pub const WRITE_LOCAL_NAME: u16 = 0x0c13;
    pub const READ_LOCAL_NAME: u16 = 0x0c14;
    pub const READ_CONNECTION_ACCEPT_TIMEOUT: u16 = 0x0c15;
    pub const WRITE_CONNECTION_ACCEPT_TIMEOUT: u16 = 0x0c16;
    pub const READ_PAGE_TIMEOUT: u16 = 0x0c17;
    pub const WRITE_PAGE_TIMEOUT: u16 = 0x0c18;
    pub const READ_SCAN_ENABLE: u16 = 0x0c19;
    pub const WRITE_SCAN_ENABLE: u16 = 0x0c1a;
    pub const READ_PAGE_SCAN_ACTIVITY: u16 = 0x0c1b;
    pub const WRITE_PAGE_SCAN_ACTIVITY: u16 = 0x0c1c;
    pub const READ_INQUIRY_SCAN_ACTIVITY: u16 = 0x0c1d;
    pub const WRITE_INQUIRY_SCAN_ACTIVITY: u16 = 0x0c1e;
    pub const READ_AUTHENTICATION_ENABLE: u16 = 0x0c1f;
    pub const WRITE_AUTHENTICATION_ENABLE: u16 = 0x0c20;
    pub const READ_ENCRYPTION_MODE: u16 = 0x0c21;
    pub const WRITE_ENCRYPTION_MODE: u16 = 0x0c22;
    pub const READ_CLASS_OF_DEVICE: u16 = 0x0c23;
    pub const WRITE_CLASS_OF_DEVICE: u16 = 0x0c24;
    pub const READ_VOICE_SETTING: u16 = 0x0c25;
    pub const WRITE_VOICE_SETTING: u16 = 0x0c26;
    pub const READ_AUTOMATIC_FLUSH_TIMEOUT: u16 = 0x0c27;
    pub const WRITE_AUTOMATIC_FLUSH_TIMEOUT: u16 = 0x0c28;
    pub const READ_NUM_BROADCAST_RETRANSMISSIONS: u16 = 0x0c29;
    pub const WRITE_NUM_BROADCAST_RETRANSMISSIONS: u16 = 0x0c2a;
    pub const READ_HOLD_MODE_ACTIVITY: u16 = 0x0c2b;
    pub const WRITE_HOLD_MODE_ACTIVITY: u16 = 0x0c2c;
    pub const READ_TRANSMIT_POWER_LEVEL: u16 = 0x0c2d;
    pub const READ_SYNCHRONOUS_FLOW_CONTROL_ENABLE: u16 = 0x0c2e;
    pub const WRITE_SYNCHRONOUS_FLOW_CONTROL_ENABLE: u16 = 0x0c2f;
    pub const SET_CONTROLLER_TO_HOST_FLOW_CONTROL: u16 = 0x0c31;
    pub const HOST_BUFFER_SIZE: u16 = 0x0c33;
    pub const HOST_NUMBER_OF_COMPLETED_PACKETS: u16 = 0x0c35;
    pub const READ_LINK_SUPERVISION_TIMEOUT: u16 = 0x0c36;
    pub const WRITE_LINK_SUPERVISION_TIMEOUT: u16 = 0x0c37;
    pub const READ_NUMBER_OF_SUPPORTED_IAC: u16 = 0x0c38;
    pub const READ_CURRENT_IAC_LAP: u16 = 0x0c39;
    pub const WRITE_CURRENT_IAC_LAP: u16 = 0x0c3a;
    pub const READ_PAGE_SCAN_PERIOD_MODE: u16 = 0x0c3b;
    pub const WRITE_PAGE_SCAN_PERIOD_MODE: u16 = 0x0c3c;
    pub const READ_PAGE_SCAN_MODE: u16 = 0x0c3d;
    pub const WRITE_PAGE_SCAN_MODE: u16 = 0x0c3e;
    pub const SET_AFH_HOST_CHANNEL_CLASSIFICATION: u16 = 0x0c3f;
    pub const READ_INQUIRY_SCAN_TYPE: u16 = 0x0c42;
    pub const WRITE_INQUIRY_SCAN_TYPE: u16 = 0x0c43;
    pub const READ_INQUIRY_MODE: u16 = 0x0c44;
    pub const WRITE_INQUIRY_MODE: u16 = 0x0c45;
    pub const READ_PAGE_SCAN_TYPE: u16 = 0x0c46;
    pub const WRITE_PAGE_SCAN_TYPE: u16 = 0x0c47;
    pub const READ_AFH_CHANNEL_ASSESSMENT_MODE: u16 = 0x0c48;
    pub const WRITE_AFH_CHANNEL_ASSESSMENT_MODE: u16 = 0x0c49;
    pub const READ_EXTENDED_INQUIRY_RESPONSE: u16 = 0x0c51;
    pub const WRITE_EXTENDED_INQUIRY_RESPONSE: u16 = 0x0c52;
    pub const REFRESH_ENCRYPTION_KEY: u16 = 0x0c53;
    pub const READ_SIMPLE_PAIRING_MODE: u16 = 0x0c55;
    pub const WRITE_SIMPLE_PAIRING_MODE: u16 = 0x0c56;
    pub const READ_LOCAL_OOB_DATA: u16 = 0x0c57;
    pub const READ_INQUIRY_RESPONSE_TRANSMIT_POWER_LEVEL: u16 = 0x0c58;
    pub const WRITE_INQUIRY_TRANSMIT_POWER_LEVEL: u16 = 0x0c59;
    pub const READ_DEFAULT_ERRONEOUS_DATA_REPORTING: u16 = 0x0c5a;
    pub const WRITE_DEFAULT_ERRONEOUS_DATA_REPORTING: u16 = 0x0c5b;
    pub const ENHANCED_FLUSH: u16 = 0x0c5f;
    pub const SEND_KEYPRESS_NOTIFICATION: u16 = 0x0c60;
    pub const READ_LOGICAL_LINK_ACCEPT_TIMEOUT: u16 = 0x0c61;
    pub const WRITE_LOGICAL_LINK_ACCEPT_TIMEOUT: u16 = 0x0c62;
    pub const SET_EVENT_MASK_PAGE_2: u16 = 0x0c63;
    pub const READ_LOCATION_DATA: u16 = 0x0c64;
    pub const WRITE_LOCATION_DATA: u16 = 0x0c65;
    pub const READ_FLOW_CONTROL_MODE: u16 = 0x0c66;
    pub const WRITE_FLOW_CONTROL_MODE: u16 = 0x0c67;
    pub const READ_ENHANCED_TRANSMIT_POWER_LEVEL: u16 = 0x0c68;
    pub const READ_BEST_EFFORT_FLUSH_TIMEOUT: u16 = 0x0c69;
    pub const WRITE_BEST_EFFORT_FLUSH_TIMEOUT: u16 = 0x0c6a;
    pub const SHORT_RANGE_MODE: u16 = 0x0c6b;
    pub const READ_LE_HOST_SUPPORT: u16 = 0x0c6c;
    pub const WRITE_LE_HOST_SUPPORT: u16 = 0x0c6d;
    pub const SET_MWS_CHANNEL_PARAMETERS: u16 = 0x0c6e;
    pub const SET_EXTERNAL_FRAME_CONFIGURATION: u16 = 0x0c6f;
    pub const SET_MWS_SIGNALING: u16 = 0x0c70;
    pub const SET_MWS_TRANSPORT_LAYER: u16 = 0x0c71;
    pub const SET_MWS_SCAN_FREQUENCY_TABLE: u16 = 0x0c72;
    pub const SET_MWS_PATTERN_CONFIGURATION: u16 = 0x0c73;
    pub const SET_RESERVED_LT_ADDR: u16 = 0x0c74;
    pub const DELETE_RESERVED_LT_ADDR: u16 = 0x0c75;
    pub const SET_CONNECTIONLESS_PERIPHERAL_BROADCAST_DATA: u16 = 0x0c76;
    pub const READ_SYNCHRONIZATION_TRAIN_PARAMETERS: u16 = 0x0c77;
    pub const WRITE_SYNCHRONIZATION_TRAIN_PARAMETERS: u16 = 0x0c78;
    pub const READ_SECURE_CONNECTIONS_HOST_SUPPORT: u16 = 0x0c79;
    pub const WRITE_SECURE_CONNECTIONS_HOST_SUPPORT: u16 = 0x0c7a;
    pub const READ_AUTHENTICATED_PAYLOAD_TIMEOUT: u16 = 0x0c7b;
    pub const WRITE_AUTHENTICATED_PAYLOAD_TIMEOUT: u16 = 0x0c7c;
    pub const READ_LOCAL_OOB_EXTENDED_DATA: u16 = 0x0c7d;
    pub const READ_EXTENDED_PAGE_TIMEOUT: u16 = 0x0c7e;
    pub const WRITE_EXTENDED_PAGE_TIMEOUT: u16 = 0x0c7f;
    pub const READ_EXTENDED_INQUIRY_LENGTH: u16 = 0x0c80;
    pub const WRITE_EXTENDED_INQUIRY_LENGTH: u16 = 0x0c81;
    pub const SET_ECOSYSTEM_BASE_INTERVAL: u16 = 0x0c82;
    pub const CONFIGURE_DATA_PATH: u16 = 0x0c83;
    pub const SET_MIN_ENCRYPTION_KEY_SIZE: u16 = 0x0c84;
    pub const READ_LOCAL_VERSION_INFORMATION: u16 = 0x1001;
    pub const READ_LOCAL_SUPPORTED_COMMANDS: u16 = 0x1002;
    pub const READ_LOCAL_SUPPORTED_FEATURES: u16 = 0x1003;
    pub const READ_LOCAL_EXTENDED_FEATURES: u16 = 0x1004;
    pub const READ_BUFFER_SIZE: u16 = 0x1005;
    pub const READ_BD_ADDR: u16 = 0x1009;
    pub const READ_DATA_BLOCK_SIZE: u16 = 0x100a;
    pub const READ_LOCAL_SUPPORTED_CODECS: u16 = 0x100b;
    pub const READ_LOCAL_SIMPLE_PAIRING_OPTIONS: u16 = 0x100c;
    pub const READ_LOCAL_SUPPORTED_CODECS_V2: u16 = 0x100d;
    pub const READ_LOCAL_SUPPORTED_CODEC_CAPABILITIES: u16 = 0x100e;
    pub const READ_LOCAL_SUPPORTED_CONTROLLER_DELAY: u16 = 0x100f;
    pub const READ_LOCAL_SUPPORTED_COMMANDS_V2: u16 = 0x1010;
    pub const READ_FAILED_CONTACT_COUNTER: u16 = 0x1401;
    pub const RESET_FAILED_CONTACT_COUNTER: u16 = 0x1402;
    pub const READ_LINK_QUALITY: u16 = 0x1403;
    pub const READ_RSSI: u16 = 0x1405;
    pub const READ_AFH_CHANNEL_MAP: u16 = 0x1406;
    pub const READ_CLOCK: u16 = 0x1407;
    pub const READ_ENCRYPTION_KEY_SIZE: u16 = 0x1408;
    pub const READ_LOCAL_AMP_INFO: u16 = 0x1409;
    pub const READ_LOCAL_AMP_ASSOC: u16 = 0x140a;
    pub const WRITE_REMOTE_AMP_ASSOC: u16 = 0x140b;
    pub const GET_MWS_TRANSPORT_LAYER_CONFIGURATION: u16 = 0x140c;
    pub const SET_TRIGGERED_CLOCK_CAPTURE: u16 = 0x140d;
    pub const READ_LOOPBACK_MODE: u16 = 0x1801;
    pub const WRITE_LOOPBACK_MODE: u16 = 0x1802;
    pub const ENABLE_IMPLEMENTATION_UNDER_TEST_MODE: u16 = 0x1803;
    pub const WRITE_SIMPLE_PAIRING_DEBUG_MODE: u16 = 0x1804;
    pub const ENABLE_AMP_RECEIVER_REPORTS: u16 = 0x1807;
    pub const AMP_TEST_END: u16 = 0x1808;
    pub const AMP_TEST: u16 = 0x1809;
    pub const WRITE_SECURE_CONNECTIONS_TEST_MODE: u16 = 0x180a;
    pub const READ_SECURE_CONNECTIONS_TEST_MODE: u16 = 0x180b;
    pub const LE_SET_EVENT_MASK: u16 = 0x2001;
    pub const LE_READ_BUFFER_SIZE: u16 = 0x2002;
    pub const LE_READ_LOCAL_SUPPORTED_FEATURES_PAGE_0: u16 = 0x2003;
    pub const LE_SET_RANDOM_ADDRESS: u16 = 0x2005;
    pub const LE_SET_ADVERTISING_PARAMETERS: u16 = 0x2006;
    pub const LE_READ_ADVERTISING_PHYSICAL_CHANNEL_TX_POWER: u16 = 0x2007;
    pub const LE_SET_ADVERTISING_DATA: u16 = 0x2008;
    pub const LE_SET_SCAN_RESPONSE_DATA: u16 = 0x2009;
    pub const LE_SET_ADVERTISING_ENABLE: u16 = 0x200a;
    pub const LE_SET_SCAN_PARAMETERS: u16 = 0x200b;
    pub const LE_SET_SCAN_ENABLE: u16 = 0x200c;
    pub const LE_CREATE_CONNECTION: u16 = 0x200d;
    pub const LE_CREATE_CONNECTION_CANCEL: u16 = 0x200e;
    pub const LE_READ_FILTER_ACCEPT_LIST_SIZE: u16 = 0x200f;
    pub const LE_CLEAR_FILTER_ACCEPT_LIST: u16 = 0x2010;
    pub const LE_ADD_DEVICE_TO_FILTER_ACCEPT_LIST: u16 = 0x2011;
    pub const LE_REMOVE_DEVICE_FROM_FILTER_ACCEPT_LIST: u16 = 0x2012;
    pub const LE_CONNECTION_UPDATE: u16 = 0x2013;
    pub const LE_SET_HOST_CHANNEL_CLASSIFICATION: u16 = 0x2014;
    pub const LE_READ_CHANNEL_MAP: u16 = 0x2015;
    pub const LE_READ_REMOTE_FEATURES_PAGE_0: u16 = 0x2016;
    pub const LE_ENCRYPT: u16 = 0x2017;
    pub const LE_RAND: u16 = 0x2018;
    pub const LE_ENABLE_ENCRYPTION: u16 = 0x2019;
    pub const LE_LONG_TERM_KEY_REQUEST_REPLY: u16 = 0x201a;
    pub const LE_LONG_TERM_KEY_REQUEST_NEGATIVE_REPLY: u16 = 0x201b;
    pub const LE_READ_SUPPORTED_STATES: u16 = 0x201c;
    pub const LE_RECEIVER_TEST: u16 = 0x201d;
    pub const LE_TRANSMITTER_TEST: u16 = 0x201e;
    pub const LE_TEST_END: u16 = 0x201f;
    pub const LE_REMOTE_CONNECTION_PARAMETER_REQUEST_REPLY: u16 = 0x2020;
    pub const LE_REMOTE_CONNECTION_PARAMETER_REQUEST_NEGATIVE_REPLY: u16 = 0x2021;
    pub const LE_SET_DATA_LENGTH: u16 = 0x2022;
    pub const LE_READ_SUGGESTED_DEFAULT_DATA_LENGTH: u16 = 0x2023;
    pub const LE_WRITE_SUGGESTED_DEFAULT_DATA_LENGTH: u16 = 0x2024;
    pub const LE_READ_LOCAL_P_256_PUBLIC_KEY: u16 = 0x2025;
    pub const LE_GENERATE_DHKEY: u16 = 0x2026;
    pub const LE_ADD_DEVICE_TO_RESOLVING_LIST: u16 = 0x2027;
    pub const LE_REMOVE_DEVICE_FROM_RESOLVING_LIST: u16 = 0x2028;
    pub const LE_CLEAR_RESOLVING_LIST: u16 = 0x2029;
    pub const LE_READ_RESOLVING_LIST_SIZE: u16 = 0x202a;
    pub const LE_READ_PEER_RESOLVABLE_ADDRESS: u16 = 0x202b;
    pub const LE_READ_LOCAL_RESOLVABLE_ADDRESS: u16 = 0x202c;
    pub const LE_SET_ADDRESS_RESOLUTION_ENABLE: u16 = 0x202d;
    pub const LE_SET_RESOLVABLE_PRIVATE_ADDRESS_TIMEOUT: u16 = 0x202e;
    pub const LE_READ_MAXIMUM_DATA_LENGTH: u16 = 0x202f;
    pub const LE_READ_PHY: u16 = 0x2030;
    pub const LE_SET_DEFAULT_PHY: u16 = 0x2031;
    pub const LE_SET_PHY: u16 = 0x2032;
    pub const LE_RECEIVER_TEST_V2: u16 = 0x2033;
    pub const LE_TRANSMITTER_TEST_V2: u16 = 0x2034;
    pub const LE_SET_ADVERTISING_SET_RANDOM_ADDRESS: u16 = 0x2035;
    pub const LE_SET_EXTENDED_ADVERTISING_PARAMETERS: u16 = 0x2036;
    pub const LE_SET_EXTENDED_ADVERTISING_DATA: u16 = 0x2037;
    pub const LE_SET_EXTENDED_SCAN_RESPONSE_DATA: u16 = 0x2038;
    pub const LE_SET_EXTENDED_ADVERTISING_ENABLE: u16 = 0x2039;
    pub const LE_READ_MAXIMUM_ADVERTISING_DATA_LENGTH: u16 = 0x203a;
    pub const LE_READ_NUMBER_OF_SUPPORTED_ADVERTISING_SETS: u16 = 0x203b;
    pub const LE_REMOVE_ADVERTISING_SET: u16 = 0x203c;
    pub const LE_CLEAR_ADVERTISING_SETS: u16 = 0x203d;
    pub const LE_SET_PERIODIC_ADVERTISING_PARAMETERS: u16 = 0x203e;
    pub const LE_SET_PERIODIC_ADVERTISING_DATA: u16 = 0x203f;
    pub const LE_SET_PERIODIC_ADVERTISING_ENABLE: u16 = 0x2040;
    pub const LE_SET_EXTENDED_SCAN_PARAMETERS: u16 = 0x2041;
    pub const LE_SET_EXTENDED_SCAN_ENABLE: u16 = 0x2042;
    pub const LE_EXTENDED_CREATE_CONNECTION: u16 = 0x2043;
    pub const LE_PERIODIC_ADVERTISING_CREATE_SYNC: u16 = 0x2044;
    pub const LE_PERIODIC_ADVERTISING_CREATE_SYNC_CANCEL: u16 = 0x2045;
    pub const LE_PERIODIC_ADVERTISING_TERMINATE_SYNC: u16 = 0x2046;
    pub const LE_ADD_DEVICE_TO_PERIODIC_ADVERTISER_LIST: u16 = 0x2047;
    pub const LE_REMOVE_DEVICE_FROM_PERIODIC_ADVERTISER_LIST: u16 = 0x2048;
    pub const LE_CLEAR_PERIODIC_ADVERTISER_LIST: u16 = 0x2049;
    pub const LE_READ_PERIODIC_ADVERTISER_LIST_SIZE: u16 = 0x204a;
    pub const LE_READ_TRANSMIT_POWER: u16 = 0x204b;
    pub const LE_READ_RF_PATH_COMPENSATION: u16 = 0x204c;
    pub const LE_WRITE_RF_PATH_COMPENSATION: u16 = 0x204d;
    pub const LE_SET_PRIVACY_MODE: u16 = 0x204e;
    pub const LE_RECEIVER_TEST_V3: u16 = 0x204f;
    pub const LE_TRANSMITTER_TEST_V3: u16 = 0x2050;
    pub const LE_SET_CONNECTIONLESS_CTE_TRANSMIT_PARAMETERS: u16 = 0x2051;
    pub const LE_SET_CONNECTIONLESS_CTE_TRANSMIT_ENABLE: u16 = 0x2052;
    pub const LE_SET_CONNECTIONLESS_IQ_SAMPLING_ENABLE: u16 = 0x2053;
    pub const LE_SET_CONNECTION_CTE_RECEIVE_PARAMETERS: u16 = 0x2054;
    pub const LE_SET_CONNECTION_CTE_TRANSMIT_PARAMETERS: u16 = 0x2055;
    pub const LE_CONNECTION_CTE_REQUEST_ENABLE: u16 = 0x2056;
    pub const LE_CONNECTION_CTE_RESPONSE_ENABLE: u16 = 0x2057;
    pub const LE_READ_ANTENNA_INFORMATION: u16 = 0x2058;
    pub const LE_SET_PERIODIC_ADVERTISING_RECEIVE_ENABLE: u16 = 0x2059;
    pub const LE_PERIODIC_ADVERTISING_SYNC_TRANSFER: u16 = 0x205a;
    pub const LE_PERIODIC_ADVERTISING_SET_INFO_TRANSFER: u16 = 0x205b;
    pub const LE_SET_PERIODIC_ADVERTISING_SYNC_TRANSFER_PARAMETERS: u16 = 0x205c;
    pub const LE_SET_DEFAULT_PERIODIC_ADVERTISING_SYNC_TRANSFER_PARAMETERS: u16 = 0x205d;
    pub const LE_GENERATE_DHKEY_V2: u16 = 0x205e;
    pub const LE_MODIFY_SLEEP_CLOCK_ACCURACY: u16 = 0x205f;
    pub const LE_READ_BUFFER_SIZE_V2: u16 = 0x2060;
    pub const LE_READ_ISO_TX_SYNC: u16 = 0x2061;
    pub const LE_SET_CIG_PARAMETERS: u16 = 0x2062;
    pub const LE_SET_CIG_PARAMETERS_TEST: u16 = 0x2063;
    pub const LE_CREATE_CIS: u16 = 0x2064;
    pub const LE_REMOVE_CIG: u16 = 0x2065;
    pub const LE_ACCEPT_CIS_REQUEST: u16 = 0x2066;
    pub const LE_REJECT_CIS_REQUEST: u16 = 0x2067;
    pub const LE_CREATE_BIG: u16 = 0x2068;
    pub const LE_CREATE_BIG_TEST: u16 = 0x2069;
    pub const LE_TERMINATE_BIG: u16 = 0x206a;
    pub const LE_BIG_CREATE_SYNC: u16 = 0x206b;
    pub const LE_BIG_TERMINATE_SYNC: u16 = 0x206c;
    pub const LE_REQUEST_PEER_SCA: u16 = 0x206d;
    pub const LE_SETUP_ISO_DATA_PATH: u16 = 0x206e;
    pub const LE_REMOVE_ISO_DATA_PATH: u16 = 0x206f;
    pub const LE_ISO_TRANSMIT_TEST: u16 = 0x2070;
    pub const LE_ISO_RECEIVE_TEST: u16 = 0x2071;
    pub const LE_ISO_READ_TEST_COUNTERS: u16 = 0x2072;
    pub const LE_ISO_TEST_END: u16 = 0x2073;
    pub const LE_SET_HOST_FEATURE: u16 = 0x2074;
    pub const LE_READ_ISO_LINK_QUALITY: u16 = 0x2075;
    pub const LE_ENHANCED_READ_TRANSMIT_POWER_LEVEL: u16 = 0x2076;
    pub const LE_READ_REMOTE_TRANSMIT_POWER_LEVEL: u16 = 0x2077;
    pub const LE_SET_PATH_LOSS_REPORTING_PARAMETERS: u16 = 0x2078;
    pub const LE_SET_PATH_LOSS_REPORTING_ENABLE: u16 = 0x2079;
    pub const LE_SET_TRANSMIT_POWER_REPORTING_ENABLE: u16 = 0x207a;
    pub const LE_TRANSMITTER_TEST_V4: u16 = 0x207b;
    pub const LE_SET_DATA_RELATED_ADDRESS_CHANGES: u16 = 0x207c;
    pub const LE_SET_DEFAULT_SUBRATE: u16 = 0x207d;
    pub const LE_SUBRATE_REQUEST: u16 = 0x207e;
    pub const LE_SET_EXTENDED_ADVERTISING_PARAMETERS_V2: u16 = 0x207f;
    pub const LE_SET_DECISION_DATA: u16 = 0x2080;
    pub const LE_SET_DECISION_INSTRUCTIONS: u16 = 0x2081;
    pub const LE_SET_PERIODIC_ADVERTISING_SUBEVENT_DATA: u16 = 0x2082;
    pub const LE_SET_PERIODIC_ADVERTISING_RESPONSE_DATA: u16 = 0x2083;
    pub const LE_SET_PERIODIC_SYNC_SUBEVENT: u16 = 0x2084;
    pub const LE_EXTENDED_CREATE_CONNECTION_V2: u16 = 0x2085;
    pub const LE_SET_PERIODIC_ADVERTISING_PARAMETERS_V2: u16 = 0x2086;
    pub const LE_READ_ALL_LOCAL_SUPPORTED_FEATURES: u16 = 0x2087;
    pub const LE_READ_ALL_REMOTE_FEATURES: u16 = 0x2088;
    pub const LE_CS_READ_LOCAL_SUPPORTED_CAPABILITIES: u16 = 0x2089;
    pub const LE_CS_READ_REMOTE_SUPPORTED_CAPABILITIES: u16 = 0x208a;
    pub const LE_CS_WRITE_CACHED_REMOTE_SUPPORTED_CAPABILITIES: u16 = 0x208b;
    pub const LE_CS_SECURITY_ENABLE: u16 = 0x208c;
    pub const LE_CS_SET_DEFAULT_SETTINGS: u16 = 0x208d;
    pub const LE_CS_READ_REMOTE_FAE_TABLE: u16 = 0x208e;
    pub const LE_CS_WRITE_CACHED_REMOTE_FAE_TABLE: u16 = 0x208f;
    pub const LE_CS_CREATE_CONFIG: u16 = 0x2090;
    pub const LE_CS_REMOVE_CONFIG: u16 = 0x2091;
    pub const LE_CS_SET_CHANNEL_CLASSIFICATION: u16 = 0x2092;
    pub const LE_CS_SET_PROCEDURE_PARAMETERS: u16 = 0x2093;
    pub const LE_CS_PROCEDURE_ENABLE: u16 = 0x2094;
    pub const LE_CS_TEST: u16 = 0x2095;
    pub const LE_CS_TEST_END: u16 = 0x2096;
    pub const LE_SET_HOST_FEATURE_V2: u16 = 0x2097;
    pub const LE_ADD_DEVICE_TO_MONITORED_ADVERTISERS_LIST: u16 = 0x2098;
    pub const LE_REMOVE_DEVICE_FROM_MONITORED_ADVERTISERS_LIST: u16 = 0x2099;
    pub const LE_CLEAR_MONITORED_ADVERTISERS_LIST: u16 = 0x209a;
    pub const LE_READ_MONITORED_ADVERTISERS_LIST_SIZE: u16 = 0x209b;
    pub const LE_ENABLE_MONITORING_ADVERTISERS: u16 = 0x209c;
    pub const LE_FRAME_SPACE_UPDATE: u16 = 0x209d;
    pub const LE_SET_RESOLVABLE_PRIVATE_ADDRESS_TIMEOUT_V2: u16 = 0x209e;
    pub const LE_ENABLE_UTP_OTA_MODE: u16 = 0x209f;
    pub const LE_UTP_SEND: u16 = 0x20a0;
    pub const LE_CONNECTION_RATE_REQUEST: u16 = 0x20a1;
    pub const LE_SET_DEFAULT_RATE_PARAMETERS: u16 = 0x20a2;
    pub const LE_READ_MINIMUM_SUPPORTED_CONNECTION_INTERVAL: u16 = 0x20a3;
    pub const LE_SET_EVENT_MASK_V2: u16 = 0x20a4;
    pub const LE_CS_READ_LOCAL_SUPPORTED_CAPABILITIES_V2: u16 = 0x20a5;
    pub const LE_CS_WRITE_CACHED_REMOTE_SUPPORTED_CAPABILITIES_V2: u16 = 0x20a6;
}

/// All known HCI commands as `(opcode, name)`, sorted by opcode.
pub static COMMANDS: &[(u16, &str)] = &[
    (0x0401, "Inquiry"),
    (0x0402, "Inquiry Cancel"),
    (0x0403, "Periodic Inquiry Mode"),
    (0x0404, "Exit Periodic Inquiry Mode"),
    (0x0405, "Create Connection"),
    (0x0406, "Disconnect"),
    (0x0407, "Add SCO Connection"),
    (0x0408, "Create Connection Cancel"),
    (0x0409, "Accept Connection Request"),
    (0x040a, "Reject Connection Request"),
    (0x040b, "Link Key Request Reply"),
    (0x040c, "Link Key Request Negative Reply"),
    (0x040d, "PIN Code Request Reply"),
    (0x040e, "PIN Code Request Negative Reply"),
    (0x040f, "Change Connection Packet Type"),
    (0x0411, "Authentication Requested"),
    (0x0413, "Set Connection Encryption"),
    (0x0415, "Change Connection Link Key"),
    (0x0417, "Link Key Selection"),
    (0x0419, "Remote Name Request"),
    (0x041a, "Remote Name Request Cancel"),
    (0x041b, "Read Remote Supported Features"),
    (0x041c, "Read Remote Extended Features"),
    (0x041d, "Read Remote Version Information"),
    (0x041f, "Read Clock Offset"),
    (0x0420, "Read LMP Handle"),
    (0x0428, "Setup Synchronous Connection"),
    (0x0429, "Accept Synchronous Connection Request"),
    (0x042a, "Reject Synchronous Connection Request"),
    (0x042b, "IO Capability Request Reply"),
    (0x042c, "User Confirmation Request Reply"),
    (0x042d, "User Confirmation Request Negative Reply"),
    (0x042e, "User Passkey Request Reply"),
    (0x042f, "User Passkey Request Negative Reply"),
    (0x0430, "Remote OOB Data Request Reply"),
    (0x0433, "Remote OOB Data Request Negative Reply"),
    (0x0434, "IO Capability Request Negative Reply"),
    (0x0435, "Create Physical Link"),
    (0x0436, "Accept Physical Link"),
    (0x0437, "Disconnect Physical Link"),
    (0x0438, "Create Logical Link"),
    (0x0439, "Accept Logical Link"),
    (0x043a, "Disconnect Logical Link"),
    (0x043b, "Logical Link Cancel"),
    (0x043c, "Flow Spec Modify"),
    (0x043d, "Enhanced Setup Synchronous Connection"),
    (0x043e, "Enhanced Accept Synchronous Connection Request"),
    (0x043f, "Truncated Page"),
    (0x0440, "Truncated Page Cancel"),
    (0x0441, "Set Connectionless Peripheral Broadcast"),
    (0x0442, "Set Connectionless Peripheral Broadcast Receive"),
    (0x0443, "Start Synchronization Train"),
    (0x0444, "Receive Synchronization Train"),
    (0x0445, "Remote OOB Extended Data Request Reply"),
    (0x0801, "Hold Mode"),
    (0x0803, "Sniff Mode"),
    (0x0804, "Exit Sniff Mode"),
    (0x0805, "Park State"),
    (0x0806, "Exit Park State"),
    (0x0807, "QoS Setup"),
    (0x0809, "Role Discovery"),
    (0x080b, "Switch Role"),
    (0x080c, "Read Link Policy Settings"),
    (0x080d, "Write Link Policy Settings"),
    (0x080e, "Read Default Link Policy Settings"),
    (0x080f, "Write Default Link Policy Settings"),
    (0x0810, "Flow Specification"),
    (0x0811, "Sniff Subrating"),
    (0x0c01, "Set Event Mask"),
    (0x0c03, "Reset"),
    (0x0c05, "Set Event Filter"),
    (0x0c08, "Flush"),
    (0x0c09, "Read PIN Type"),
    (0x0c0a, "Write PIN Type"),
    (0x0c0b, "Create New Unit Key"),
    (0x0c0d, "Read Stored Link Key"),
    (0x0c11, "Write Stored Link Key"),
    (0x0c12, "Delete Stored Link Key"),
    (0x0c13, "Write Local Name"),
    (0x0c14, "Read Local Name"),
    (0x0c15, "Read Connection Accept Timeout"),
    (0x0c16, "Write Connection Accept Timeout"),
    (0x0c17, "Read Page Timeout"),
    (0x0c18, "Write Page Timeout"),
    (0x0c19, "Read Scan Enable"),
    (0x0c1a, "Write Scan Enable"),
    (0x0c1b, "Read Page Scan Activity"),
    (0x0c1c, "Write Page Scan Activity"),
    (0x0c1d, "Read Inquiry Scan Activity"),
    (0x0c1e, "Write Inquiry Scan Activity"),
    (0x0c1f, "Read Authentication Enable"),
    (0x0c20, "Write Authentication Enable"),
    (0x0c21, "Read Encryption Mode"),
    (0x0c22, "Write Encryption Mode"),
    (0x0c23, "Read Class of Device"),
    (0x0c24, "Write Class of Device"),
    (0x0c25, "Read Voice Setting"),
    (0x0c26, "Write Voice Setting"),
    (0x0c27, "Read Automatic Flush Timeout"),
    (0x0c28, "Write Automatic Flush Timeout"),
    (0x0c29, "Read Num Broadcast Retransmissions"),
    (0x0c2a, "Write Num Broadcast Retransmissions"),
    (0x0c2b, "Read Hold Mode Activity"),
    (0x0c2c, "Write Hold Mode Activity"),
    (0x0c2d, "Read Transmit Power Level"),
    (0x0c2e, "Read Synchronous Flow Control Enable"),
    (0x0c2f, "Write Synchronous Flow Control Enable"),
    (0x0c31, "Set Controller To Host Flow Control"),
    (0x0c33, "Host Buffer Size"),
    (0x0c35, "Host Number Of Completed Packets"),
    (0x0c36, "Read Link Supervision Timeout"),
    (0x0c37, "Write Link Supervision Timeout"),
    (0x0c38, "Read Number Of Supported IAC"),
    (0x0c39, "Read Current IAC LAP"),
    (0x0c3a, "Write Current IAC LAP"),
    (0x0c3b, "Read Page Scan Period Mode"),
    (0x0c3c, "Write Page Scan Period Mode"),
    (0x0c3d, "Read Page Scan Mode"),
    (0x0c3e, "Write Page Scan Mode"),
    (0x0c3f, "Set AFH Host Channel Classification"),
    (0x0c42, "Read Inquiry Scan Type"),
    (0x0c43, "Write Inquiry Scan Type"),
    (0x0c44, "Read Inquiry Mode"),
    (0x0c45, "Write Inquiry Mode"),
    (0x0c46, "Read Page Scan Type"),
    (0x0c47, "Write Page Scan Type"),
    (0x0c48, "Read AFH Channel Assessment Mode"),
    (0x0c49, "Write AFH Channel Assessment Mode"),
    (0x0c51, "Read Extended Inquiry Response"),
    (0x0c52, "Write Extended Inquiry Response"),
    (0x0c53, "Refresh Encryption Key"),
    (0x0c55, "Read Simple Pairing Mode"),
    (0x0c56, "Write Simple Pairing Mode"),
    (0x0c57, "Read Local OOB Data"),
    (0x0c58, "Read Inquiry Response Transmit Power Level"),
    (0x0c59, "Write Inquiry Transmit Power Level"),
    (0x0c5a, "Read Default Erroneous Data Reporting"),
    (0x0c5b, "Write Default Erroneous Data Reporting"),
    (0x0c5f, "Enhanced Flush"),
    (0x0c60, "Send Keypress Notification"),
    (0x0c61, "Read Logical Link Accept Timeout"),
    (0x0c62, "Write Logical Link Accept Timeout"),
    (0x0c63, "Set Event Mask Page 2"),
    (0x0c64, "Read Location Data"),
    (0x0c65, "Write Location Data"),
    (0x0c66, "Read Flow Control Mode"),
    (0x0c67, "Write Flow Control Mode"),
    (0x0c68, "Read Enhanced Transmit Power Level"),
    (0x0c69, "Read Best Effort Flush Timeout"),
    (0x0c6a, "Write Best Effort Flush Timeout"),
    (0x0c6b, "Short Range Mode"),
    (0x0c6c, "Read LE Host Support"),
    (0x0c6d, "Write LE Host Support"),
    (0x0c6e, "Set MWS Channel Parameters"),
    (0x0c6f, "Set External Frame Configuration"),
    (0x0c70, "Set MWS Signaling"),
    (0x0c71, "Set MWS Transport Layer"),
    (0x0c72, "Set MWS Scan Frequency Table"),
    (0x0c73, "Set MWS_PATTERN Configuration"),
    (0x0c74, "Set Reserved LT_ADDR"),
    (0x0c75, "Delete Reserved LT_ADDR"),
    (0x0c76, "Set Connectionless Peripheral Broadcast Data"),
    (0x0c77, "Read Synchronization Train Parameters"),
    (0x0c78, "Write Synchronization Train Parameters"),
    (0x0c79, "Read Secure Connections Host Support"),
    (0x0c7a, "Write Secure Connections Host Support"),
    (0x0c7b, "Read Authenticated Payload Timeout"),
    (0x0c7c, "Write Authenticated Payload Timeout"),
    (0x0c7d, "Read Local OOB Extended Data"),
    (0x0c7e, "Read Extended Page Timeout"),
    (0x0c7f, "Write Extended Page Timeout"),
    (0x0c80, "Read Extended Inquiry Length"),
    (0x0c81, "Write Extended Inquiry Length"),
    (0x0c82, "Set Ecosystem Base Interval"),
    (0x0c83, "Configure Data Path"),
    (0x0c84, "Set Min Encryption Key Size"),
    (0x1001, "Read Local Version Information"),
    (0x1002, "Read Local Supported Commands"),
    (0x1003, "Read Local Supported Features"),
    (0x1004, "Read Local Extended Features"),
    (0x1005, "Read Buffer Size"),
    (0x1009, "Read BD_ADDR"),
    (0x100a, "Read Data Block Size"),
    (0x100b, "Read Local Supported Codecs"),
    (0x100c, "Read Local Simple Pairing Options"),
    (0x100d, "Read Local Supported Codecs v2"),
    (0x100e, "Read Local Supported Codec Capabilities"),
    (0x100f, "Read Local Supported Controller Delay"),
    (0x1010, "Read Local Supported Commands v2"),
    (0x1401, "Read Failed Contact Counter"),
    (0x1402, "Reset Failed Contact Counter"),
    (0x1403, "Read Link Quality"),
    (0x1405, "Read RSSI"),
    (0x1406, "Read AFH Channel Map"),
    (0x1407, "Read Clock"),
    (0x1408, "Read Encryption Key Size"),
    (0x1409, "Read Local AMP Info"),
    (0x140a, "Read Local AMP ASSOC"),
    (0x140b, "Write Remote AMP ASSOC"),
    (0x140c, "Get MWS Transport Layer Configuration"),
    (0x140d, "Set Triggered Clock Capture"),
    (0x1801, "Read Loopback Mode"),
    (0x1802, "Write Loopback Mode"),
    (0x1803, "Enable Implementation Under Test Mode"),
    (0x1804, "Write Simple Pairing Debug Mode"),
    (0x1807, "Enable AMP Receiver Reports"),
    (0x1808, "AMP Test End"),
    (0x1809, "AMP Test"),
    (0x180a, "Write Secure Connections Test Mode"),
    (0x180b, "Read Secure Connections Test Mode"),
    (0x2001, "LE Set Event Mask"),
    (0x2002, "LE Read Buffer Size"),
    (0x2003, "LE Read Local Supported Features Page 0"),
    (0x2005, "LE Set Random Address"),
    (0x2006, "LE Set Advertising Parameters"),
    (0x2007, "LE Read Advertising Physical Channel Tx Power"),
    (0x2008, "LE Set Advertising Data"),
    (0x2009, "LE Set Scan Response Data"),
    (0x200a, "LE Set Advertising Enable"),
    (0x200b, "LE Set Scan Parameters"),
    (0x200c, "LE Set Scan Enable"),
    (0x200d, "LE Create Connection"),
    (0x200e, "LE Create Connection Cancel"),
    (0x200f, "LE Read Filter Accept List Size"),
    (0x2010, "LE Clear Filter Accept List"),
    (0x2011, "LE Add Device To Filter Accept List"),
    (0x2012, "LE Remove Device From Filter Accept List"),
    (0x2013, "LE Connection Update"),
    (0x2014, "LE Set Host Channel Classification"),
    (0x2015, "LE Read Channel Map"),
    (0x2016, "LE Read Remote Features Page 0"),
    (0x2017, "LE Encrypt"),
    (0x2018, "LE Rand"),
    (0x2019, "LE Enable Encryption"),
    (0x201a, "LE Long Term Key Request Reply"),
    (0x201b, "LE Long Term Key Request Negative Reply"),
    (0x201c, "LE Read Supported States"),
    (0x201d, "LE Receiver Test"),
    (0x201e, "LE Transmitter Test"),
    (0x201f, "LE Test End"),
    (0x2020, "LE Remote Connection Parameter Request Reply"),
    (0x2021, "LE Remote Connection Parameter Request Negative Reply"),
    (0x2022, "LE Set Data Length"),
    (0x2023, "LE Read Suggested Default Data Length"),
    (0x2024, "LE Write Suggested Default Data Length"),
    (0x2025, "LE Read Local P-256 Public Key"),
    (0x2026, "LE Generate DHKey"),
    (0x2027, "LE Add Device To Resolving List"),
    (0x2028, "LE Remove Device From Resolving List"),
    (0x2029, "LE Clear Resolving List"),
    (0x202a, "LE Read Resolving List Size"),
    (0x202b, "LE Read Peer Resolvable Address"),
    (0x202c, "LE Read Local Resolvable Address"),
    (0x202d, "LE Set Address Resolution Enable"),
    (0x202e, "LE Set Resolvable Private Address Timeout"),
    (0x202f, "LE Read Maximum Data Length"),
    (0x2030, "LE Read PHY"),
    (0x2031, "LE Set Default PHY"),
    (0x2032, "LE Set PHY"),
    (0x2033, "LE Receiver Test v2"),
    (0x2034, "LE Transmitter Test v2"),
    (0x2035, "LE Set Advertising Set Random Address"),
    (0x2036, "LE Set Extended Advertising Parameters"),
    (0x2037, "LE Set Extended Advertising Data"),
    (0x2038, "LE Set Extended Scan Response Data"),
    (0x2039, "LE Set Extended Advertising Enable"),
    (0x203a, "LE Read Maximum Advertising Data Length"),
    (0x203b, "LE Read Number of Supported Advertising Sets"),
    (0x203c, "LE Remove Advertising Set"),
    (0x203d, "LE Clear Advertising Sets"),
    (0x203e, "LE Set Periodic Advertising Parameters"),
    (0x203f, "LE Set Periodic Advertising Data"),
    (0x2040, "LE Set Periodic Advertising Enable"),
    (0x2041, "LE Set Extended Scan Parameters"),
    (0x2042, "LE Set Extended Scan Enable"),
    (0x2043, "LE Extended Create Connection"),
    (0x2044, "LE Periodic Advertising Create Sync"),
    (0x2045, "LE Periodic Advertising Create Sync Cancel"),
    (0x2046, "LE Periodic Advertising Terminate Sync"),
    (0x2047, "LE Add Device To Periodic Advertiser List"),
    (0x2048, "LE Remove Device From Periodic Advertiser List"),
    (0x2049, "LE Clear Periodic Advertiser List"),
    (0x204a, "LE Read Periodic Advertiser List Size"),
    (0x204b, "LE Read Transmit Power"),
    (0x204c, "LE Read RF Path Compensation"),
    (0x204d, "LE Write RF Path Compensation"),
    (0x204e, "LE Set Privacy Mode"),
    (0x204f, "LE Receiver Test v3"),
    (0x2050, "LE Transmitter Test v3"),
    (0x2051, "LE Set Connectionless CTE Transmit Parameters"),
    (0x2052, "LE Set Connectionless CTE Transmit Enable"),
    (0x2053, "LE Set Connectionless IQ Sampling Enable"),
    (0x2054, "LE Set Connection CTE Receive Parameters"),
    (0x2055, "LE Set Connection CTE Transmit Parameters"),
    (0x2056, "LE Connection CTE Request Enable"),
    (0x2057, "LE Connection CTE Response Enable"),
    (0x2058, "LE Read Antenna Information"),
    (0x2059, "LE Set Periodic Advertising Receive Enable"),
    (0x205a, "LE Periodic Advertising Sync Transfer"),
    (0x205b, "LE Periodic Advertising Set Info Transfer"),
    (0x205c, "LE Set Periodic Advertising Sync Transfer Parameters"),
    (0x205d, "LE Set Default Periodic Advertising Sync Transfer Parameters"),
    (0x205e, "LE Generate DHKey v2"),
    (0x205f, "LE Modify Sleep Clock Accuracy"),
    (0x2060, "LE Read Buffer Size v2"),
    (0x2061, "LE Read ISO TX Sync"),
    (0x2062, "LE Set CIG Parameters"),
    (0x2063, "LE Set CIG Parameters Test"),
    (0x2064, "LE Create CIS"),
    (0x2065, "LE Remove CIG"),
    (0x2066, "LE Accept CIS Request"),
    (0x2067, "LE Reject CIS Request"),
    (0x2068, "LE Create BIG"),
    (0x2069, "LE Create BIG Test"),
    (0x206a, "LE Terminate BIG"),
    (0x206b, "LE BIG Create Sync"),
    (0x206c, "LE BIG Terminate Sync"),
    (0x206d, "LE Request Peer SCA"),
    (0x206e, "LE Setup ISO Data Path"),
    (0x206f, "LE Remove ISO Data Path"),
    (0x2070, "LE ISO Transmit Test"),
    (0x2071, "LE ISO Receive Test"),
    (0x2072, "LE ISO Read Test Counters"),
    (0x2073, "LE ISO Test End"),
    (0x2074, "LE Set Host Feature"),
    (0x2075, "LE Read ISO Link Quality"),
    (0x2076, "LE Enhanced Read Transmit Power Level"),
    (0x2077, "LE Read Remote Transmit Power Level"),
    (0x2078, "LE Set Path Loss Reporting Parameters"),
    (0x2079, "LE Set Path Loss Reporting Enable"),
    (0x207a, "LE Set Transmit Power Reporting Enable"),
    (0x207b, "LE Transmitter Test v4"),
    (0x207c, "LE Set Data Related Address Changes"),
    (0x207d, "LE Set Default Subrate"),
    (0x207e, "LE Subrate Request"),
    (0x207f, "LE Set Extended Advertising Parameters v2"),
    (0x2080, "LE Set Decision Data"),
    (0x2081, "LE Set Decision Instructions"),
    (0x2082, "LE Set Periodic Advertising Subevent Data"),
    (0x2083, "LE Set Periodic Advertising Response Data"),
    (0x2084, "LE Set Periodic Sync Subevent"),
    (0x2085, "LE Extended Create Connection v2"),
    (0x2086, "LE Set Periodic Advertising Parameters v2"),
    (0x2087, "LE Read All Local Supported Features"),
    (0x2088, "LE Read All Remote Features"),
    (0x2089, "LE CS Read Local Supported Capabilities"),
    (0x208a, "LE CS Read Remote Supported Capabilities"),
    (0x208b, "LE CS Write Cached Remote Supported Capabilities"),
    (0x208c, "LE CS Security Enable"),
    (0x208d, "LE CS Set Default Settings"),
    (0x208e, "LE CS Read Remote FAE Table"),
    (0x208f, "LE CS Write Cached Remote FAE Table"),
    (0x2090, "LE CS Create Config"),
    (0x2091, "LE CS Remove Config"),
    (0x2092, "LE CS Set Channel Classification"),
    (0x2093, "LE CS Set Procedure Parameters"),
    (0x2094, "LE CS Procedure Enable"),
    (0x2095, "LE CS Test"),
    (0x2096, "LE CS Test End"),
    (0x2097, "LE Set Host Feature v2"),
    (0x2098, "LE Add Device To Monitored Advertisers List"),
    (0x2099, "LE Remove Device From Monitored Advertisers List"),
    (0x209a, "LE Clear Monitored Advertisers List"),
    (0x209b, "LE Read Monitored Advertisers List Size"),
    (0x209c, "LE Enable Monitoring Advertisers"),
    (0x209d, "LE Frame Space Update"),
    (0x209e, "LE Set Resolvable Private Address Timeout v2"),
    (0x209f, "LE Enable UTP OTA mode"),
    (0x20a0, "LE UTP Send"),
    (0x20a1, "LE Connection Rate Request"),
    (0x20a2, "LE Set Default Rate Parameters"),
    (0x20a3, "LE Read Minimum Supported Connection Interval"),
    (0x20a4, "LE Set Event Mask v2"),
    (0x20a5, "LE CS Read Local Supported Capabilities v2"),
    (0x20a6, "LE CS Write Cached Remote Supported Capabilities v2"),
];

/// HCI event codes.
pub mod evt {
    pub const INQUIRY_COMPLETE: u8 = 0x01;
    pub const INQUIRY_RESULT: u8 = 0x02;
    pub const CONNECTION_COMPLETE: u8 = 0x03;
    pub const CONNECTION_REQUEST: u8 = 0x04;
    pub const DISCONNECTION_COMPLETE: u8 = 0x05;
    pub const AUTHENTICATION_COMPLETE: u8 = 0x06;
    pub const REMOTE_NAME_REQUEST_COMPLETE: u8 = 0x07;
    pub const ENCRYPTION_CHANGE: u8 = 0x08;
    pub const CHANGE_CONNECTION_LINK_KEY_COMPLETE: u8 = 0x09;
    pub const LINK_KEY_TYPE_CHANGED: u8 = 0x0a;
    pub const READ_REMOTE_SUPPORTED_FEATURES_COMPLETE: u8 = 0x0b;
    pub const READ_REMOTE_VERSION_INFORMATION_COMPLETE: u8 = 0x0c;
    pub const QOS_SETUP_COMPLETE: u8 = 0x0d;
    pub const COMMAND_COMPLETE: u8 = 0x0e;
    pub const COMMAND_STATUS: u8 = 0x0f;
    pub const HARDWARE_ERROR: u8 = 0x10;
    pub const FLUSH_OCCURRED: u8 = 0x11;
    pub const ROLE_CHANGE: u8 = 0x12;
    pub const NUMBER_OF_COMPLETED_PACKETS: u8 = 0x13;
    pub const MODE_CHANGE: u8 = 0x14;
    pub const RETURN_LINK_KEYS: u8 = 0x15;
    pub const PIN_CODE_REQUEST: u8 = 0x16;
    pub const LINK_KEY_REQUEST: u8 = 0x17;
    pub const LINK_KEY_NOTIFICATION: u8 = 0x18;
    pub const LOOPBACK_COMMAND: u8 = 0x19;
    pub const DATA_BUFFER_OVERFLOW: u8 = 0x1a;
    pub const MAX_SLOTS_CHANGE: u8 = 0x1b;
    pub const READ_CLOCK_OFFSET_COMPLETE: u8 = 0x1c;
    pub const CONNECTION_PACKET_TYPE_CHANGED: u8 = 0x1d;
    pub const QOS_VIOLATION: u8 = 0x1e;
    pub const PAGE_SCAN_MODE_CHANGE: u8 = 0x1f;
    pub const PAGE_SCAN_REPETITION_MODE_CHANGE: u8 = 0x20;
    pub const FLOW_SPECIFICATION_COMPLETE: u8 = 0x21;
    pub const INQUIRY_RESULT_WITH_RSSI: u8 = 0x22;
    pub const READ_REMOTE_EXTENDED_FEATURES_COMPLETE: u8 = 0x23;
    pub const SYNCHRONOUS_CONNECTION_COMPLETE: u8 = 0x2c;
    pub const SYNCHRONOUS_CONNECTION_CHANGED: u8 = 0x2d;
    pub const SNIFF_SUBRATING: u8 = 0x2e;
    pub const EXTENDED_INQUIRY_RESULT: u8 = 0x2f;
    pub const ENCRYPTION_KEY_REFRESH_COMPLETE: u8 = 0x30;
    pub const IO_CAPABILITY_REQUEST: u8 = 0x31;
    pub const IO_CAPABILITY_RESPONSE: u8 = 0x32;
    pub const USER_CONFIRMATION_REQUEST: u8 = 0x33;
    pub const USER_PASSKEY_REQUEST: u8 = 0x34;
    pub const REMOTE_OOB_DATA_REQUEST: u8 = 0x35;
    pub const SIMPLE_PAIRING_COMPLETE: u8 = 0x36;
    pub const SIMPLE_PAIRING_OPTIONS: u8 = 0x37;
    pub const LINK_SUPERVISION_TIMEOUT_CHANGED: u8 = 0x38;
    pub const ENHANCED_FLUSH_COMPLETE: u8 = 0x39;
    pub const RESERVED: u8 = 0x3a;
    pub const USER_PASSKEY_NOTIFICATION: u8 = 0x3b;
    pub const KEYPRESS_NOTIFICATION: u8 = 0x3c;
    pub const REMOTE_HOST_SUPPORTED_FEATURES_NOTIFICATION: u8 = 0x3d;
    pub const LE_META: u8 = 0x3e;
    pub const PHYSICAL_LINK_COMPLETE: u8 = 0x40;
    pub const CHANNEL_SELECTED: u8 = 0x41;
    pub const DISCONNECTION_PHYSICAL_LINK_COMPLETE: u8 = 0x42;
    pub const PHYSICAL_LINK_LOSS_EARLY_WARNING: u8 = 0x43;
    pub const PHYSICAL_LINK_RECOVERY: u8 = 0x44;
    pub const LOGICAL_LINK_COMPLETE: u8 = 0x45;
    pub const DISCONNECTION_LOGICAL_LINK_COMPLETE: u8 = 0x46;
    pub const FLOW_SPEC_MODIFY_COMPLETE: u8 = 0x47;
    pub const NUMBER_OF_COMPLETED_DATA_BLOCKS: u8 = 0x48;
    pub const AMP_START_TEST: u8 = 0x49;
    pub const AMP_TEST_END: u8 = 0x4a;
    pub const AMP_RECEIVER_REPORT: u8 = 0x4b;
    pub const SHORT_RANGE_MODE_CHANGE_COMPLETE: u8 = 0x4c;
    pub const AMP_STATUS_CHANGE: u8 = 0x4d;
    pub const TRIGGERED_CLOCK_CAPTURE: u8 = 0x4e;
    pub const SYNCHRONIZATION_TRAIN_COMPLETE: u8 = 0x4f;
    pub const SYNCHRONIZATION_TRAIN_RECEIVED: u8 = 0x50;
    pub const CONNECTIONLESS_PERIPHERAL_BROADCAST_RECEIVE: u8 = 0x51;
    pub const CONNECTIONLESS_PERIPHERAL_BROADCAST_TIMEOUT: u8 = 0x52;
    pub const TRUNCATED_PAGE_COMPLETE: u8 = 0x53;
    pub const PERIPHERAL_PAGE_RESPONSE_TIMEOUT: u8 = 0x54;
    pub const CONNECTIONLESS_PERIPHERAL_BROADCAST_CHANNEL_MAP_CHANGE: u8 = 0x55;
    pub const INQUIRY_RESPONSE_NOTIFICATION: u8 = 0x56;
    pub const AUTHENTICATED_PAYLOAD_TIMEOUT_EXPIRED: u8 = 0x57;
    pub const SAM_STATUS_CHANGE: u8 = 0x58;
    pub const ENCRYPTION_CHANGE_V2: u8 = 0x59;
}

/// All known HCI events as `(event code, name)`, sorted by code.
pub static EVENTS: &[(u8, &str)] = &[
    (0x01, "Inquiry Complete"),
    (0x02, "Inquiry Result"),
    (0x03, "Connection Complete"),
    (0x04, "Connection Request"),
    (0x05, "Disconnection Complete"),
    (0x06, "Authentication Complete"),
    (0x07, "Remote Name Request Complete"),
    (0x08, "Encryption Change"),
    (0x09, "Change Connection Link Key Complete"),
    (0x0a, "Link Key Type Changed"),
    (0x0b, "Read Remote Supported Features Complete"),
    (0x0c, "Read Remote Version Information Complete"),
    (0x0d, "QoS Setup Complete"),
    (0x0e, "Command Complete"),
    (0x0f, "Command Status"),
    (0x10, "Hardware Error"),
    (0x11, "Flush Occurred"),
    (0x12, "Role Change"),
    (0x13, "Number Of Completed Packets"),
    (0x14, "Mode Change"),
    (0x15, "Return Link Keys"),
    (0x16, "PIN Code Request"),
    (0x17, "Link Key Request"),
    (0x18, "Link Key Notification"),
    (0x19, "Loopback Command"),
    (0x1a, "Data Buffer Overflow"),
    (0x1b, "Max Slots Change"),
    (0x1c, "Read Clock Offset Complete"),
    (0x1d, "Connection Packet Type Changed"),
    (0x1e, "QoS Violation"),
    (0x1f, "Page Scan Mode Change"),
    (0x20, "Page Scan Repetition Mode Change"),
    (0x21, "Flow Specification Complete"),
    (0x22, "Inquiry Result with RSSI"),
    (0x23, "Read Remote Extended Features Complete"),
    (0x2c, "Synchronous Connection Complete"),
    (0x2d, "Synchronous Connection Changed"),
    (0x2e, "Sniff Subrating"),
    (0x2f, "Extended Inquiry Result"),
    (0x30, "Encryption Key Refresh Complete"),
    (0x31, "IO Capability Request"),
    (0x32, "IO Capability Response"),
    (0x33, "User Confirmation Request"),
    (0x34, "User Passkey Request"),
    (0x35, "Remote OOB Data Request"),
    (0x36, "Simple Pairing Complete"),
    (0x37, "Simple Pairing Options"),
    (0x38, "Link Supervision Timeout Changed"),
    (0x39, "Enhanced Flush Complete"),
    (0x3a, "Reserved"),
    (0x3b, "User Passkey Notification"),
    (0x3c, "Keypress Notification"),
    (0x3d, "Remote Host Supported Features Notification"),
    (0x3e, "LE Meta"),
    (0x40, "Physical Link Complete"),
    (0x41, "Channel Selected"),
    (0x42, "Disconnection Physical Link Complete"),
    (0x43, "Physical Link Loss Early Warning"),
    (0x44, "Physical Link Recovery"),
    (0x45, "Logical Link Complete"),
    (0x46, "Disconnection Logical Link Complete"),
    (0x47, "Flow Spec Modify Complete"),
    (0x48, "Number Of Completed Data Blocks"),
    (0x49, "AMP Start Test"),
    (0x4a, "AMP Test End"),
    (0x4b, "AMP Receiver Report"),
    (0x4c, "Short Range Mode Change Complete"),
    (0x4d, "AMP Status Change"),
    (0x4e, "Triggered Clock Capture"),
    (0x4f, "Synchronization Train Complete"),
    (0x50, "Synchronization Train Received"),
    (0x51, "Connectionless Peripheral Broadcast Receive"),
    (0x52, "Connectionless Peripheral Broadcast Timeout"),
    (0x53, "Truncated Page Complete"),
    (0x54, "Peripheral Page Response Timeout"),
    (0x55, "Connectionless Peripheral Broadcast Channel Map Change"),
    (0x56, "Inquiry Response Notification"),
    (0x57, "Authenticated Payload Timeout Expired"),
    (0x58, "SAM Status Change"),
    (0x59, "Encryption Change v2"),
];

/// LE Meta event subevent codes.
pub mod le_evt {
    pub const CONNECTION_COMPLETE: u8 = 0x01;
    pub const ADVERTISING_REPORT: u8 = 0x02;
    pub const CONNECTION_UPDATE_COMPLETE: u8 = 0x03;
    pub const READ_REMOTE_FEATURES_PAGE_0_COMPLETE: u8 = 0x04;
    pub const LONG_TERM_KEY_REQUEST: u8 = 0x05;
    pub const REMOTE_CONNECTION_PARAMETER_REQUEST: u8 = 0x06;
    pub const DATA_LENGTH_CHANGE: u8 = 0x07;
    pub const READ_LOCAL_P_256_PUBLIC_KEY_COMPLETE: u8 = 0x08;
    pub const GENERATE_DHKEY_COMPLETE: u8 = 0x09;
    pub const ENHANCED_CONNECTION_COMPLETE: u8 = 0x0a;
    pub const DIRECTED_ADVERTISING_REPORT: u8 = 0x0b;
    pub const PHY_UPDATE_COMPLETE: u8 = 0x0c;
    pub const EXTENDED_ADVERTISING_REPORT: u8 = 0x0d;
    pub const PERIODIC_ADVERTISING_SYNC_ESTABLISHED: u8 = 0x0e;
    pub const PERIODIC_ADVERTISING_REPORT: u8 = 0x0f;
    pub const PERIODIC_ADVERTISING_SYNC_LOST: u8 = 0x10;
    pub const SCAN_TIMEOUT: u8 = 0x11;
    pub const ADVERTISING_SET_TERMINATED: u8 = 0x12;
    pub const SCAN_REQUEST_RECEIVED: u8 = 0x13;
    pub const CHANNEL_SELECTION_ALGORITHM: u8 = 0x14;
    pub const CONNECTIONLESS_IQ_REPORT: u8 = 0x15;
    pub const CONNECTION_IQ_REPORT: u8 = 0x16;
    pub const CTE_REQUEST_FAILED: u8 = 0x17;
    pub const PERIODIC_ADVERTISING_SYNC_TRANSFER_RECEIVED: u8 = 0x18;
    pub const CIS_ESTABLISHED: u8 = 0x19;
    pub const CIS_REQUEST: u8 = 0x1a;
    pub const CREATE_BIG_COMPLETE: u8 = 0x1b;
    pub const TERMINATE_BIG_COMPLETE: u8 = 0x1c;
    pub const BIG_SYNC_ESTABLISHED: u8 = 0x1d;
    pub const BIG_SYNC_LOST: u8 = 0x1e;
    pub const REQUEST_PEER_SCA_COMPLETE: u8 = 0x1f;
    pub const PATH_LOSS_THRESHOLD: u8 = 0x20;
    pub const TRANSMIT_POWER_REPORTING: u8 = 0x21;
    pub const BIGINFO_ADVERTISING_REPORT: u8 = 0x22;
    pub const SUBRATE_CHANGE: u8 = 0x23;
    pub const PERIODIC_ADVERTISING_SYNC_ESTABLISHED_V2: u8 = 0x24;
    pub const PERIODIC_ADVERTISING_REPORT_V2: u8 = 0x25;
    pub const PERIODIC_ADVERTISING_SYNC_TRANSFER_RECEIVED_V2: u8 = 0x26;
    pub const PERIODIC_ADVERTISING_SUBEVENT_DATA_REQUEST: u8 = 0x27;
    pub const PERIODIC_ADVERTISING_RESPONSE_REPORT: u8 = 0x28;
    pub const ENHANCED_CONNECTION_COMPLETE_V2: u8 = 0x29;
    pub const CIS_ESTABLISHED_V2: u8 = 0x2a;
    pub const READ_ALL_REMOTE_FEATURES_COMPLETE: u8 = 0x2b;
    pub const CS_READ_REMOTE_SUPPORTED_CAPABILITIES_COMPLETE: u8 = 0x2c;
    pub const CS_READ_REMOTE_FAE_TABLE_COMPLETE: u8 = 0x2d;
    pub const CS_SECURITY_ENABLE_COMPLETE: u8 = 0x2e;
    pub const CS_CONFIG_COMPLETE: u8 = 0x2f;
    pub const CS_PROCEDURE_ENABLE_COMPLETE: u8 = 0x30;
    pub const CS_SUBEVENT_RESULT: u8 = 0x31;
    pub const CS_SUBEVENT_RESULT_CONTINUE: u8 = 0x32;
    pub const CS_TEST_END_COMPLETE: u8 = 0x33;
    pub const MONITORED_ADVERTISERS_REPORT: u8 = 0x34;
    pub const FRAME_SPACE_UPDATE_COMPLETE: u8 = 0x35;
    pub const UTP_RECEIVE: u8 = 0x36;
    pub const CONNECTION_RATE_CHANGE: u8 = 0x37;
    pub const CS_READ_REMOTE_SUPPORTED_CAPABILITIES_COMPLETE_V2: u8 = 0x38;
}

/// All known LE subevents as `(subevent code, name)`, sorted by code.
pub static LE_EVENTS: &[(u8, &str)] = &[
    (0x01, "LE Connection Complete"),
    (0x02, "LE Advertising Report"),
    (0x03, "LE Connection Update Complete"),
    (0x04, "LE Read Remote Features Page 0 Complete"),
    (0x05, "LE Long Term Key Request"),
    (0x06, "LE Remote Connection Parameter Request"),
    (0x07, "LE Data Length Change"),
    (0x08, "LE Read Local P-256 Public Key Complete"),
    (0x09, "LE Generate DHKey Complete"),
    (0x0a, "LE Enhanced Connection Complete"),
    (0x0b, "LE Directed Advertising Report"),
    (0x0c, "LE PHY Update Complete"),
    (0x0d, "LE Extended Advertising Report"),
    (0x0e, "LE Periodic Advertising Sync Established"),
    (0x0f, "LE Periodic Advertising Report"),
    (0x10, "LE Periodic Advertising Sync Lost"),
    (0x11, "LE Scan Timeout"),
    (0x12, "LE Advertising Set Terminated"),
    (0x13, "LE Scan Request Received"),
    (0x14, "LE Channel Selection Algorithm"),
    (0x15, "LE Connectionless IQ Report"),
    (0x16, "LE Connection IQ Report"),
    (0x17, "LE CTE Request Failed"),
    (0x18, "LE Periodic Advertising Sync Transfer Received"),
    (0x19, "LE CIS Established"),
    (0x1a, "LE CIS Request"),
    (0x1b, "LE Create BIG Complete"),
    (0x1c, "LE Terminate BIG Complete"),
    (0x1d, "LE BIG Sync Established"),
    (0x1e, "LE BIG Sync Lost"),
    (0x1f, "LE Request Peer SCA Complete"),
    (0x20, "LE Path Loss Threshold"),
    (0x21, "LE Transmit Power Reporting"),
    (0x22, "LE BIGInfo Advertising Report"),
    (0x23, "LE Subrate Change"),
    (0x24, "LE Periodic Advertising Sync Established v2"),
    (0x25, "LE Periodic Advertising Report v2"),
    (0x26, "LE Periodic Advertising Sync Transfer Received v2"),
    (0x27, "LE Periodic Advertising Subevent Data Request"),
    (0x28, "LE Periodic Advertising Response Report"),
    (0x29, "LE Enhanced Connection Complete v2"),
    (0x2a, "LE CIS Established v2"),
    (0x2b, "LE Read All Remote Features Complete"),
    (0x2c, "LE CS Read Remote Supported Capabilities Complete"),
    (0x2d, "LE CS Read Remote FAE Table Complete"),
    (0x2e, "LE CS Security Enable Complete"),
    (0x2f, "LE CS Config Complete"),
    (0x30, "LE CS Procedure Enable Complete"),
    (0x31, "LE CS Subevent Result"),
    (0x32, "LE CS Subevent Result Continue"),
    (0x33, "LE CS Test End Complete"),
    (0x34, "LE Monitored Advertisers Report"),
    (0x35, "LE Frame Space Update Complete"),
    (0x36, "LE UTP Receive"),
    (0x37, "LE Connection Rate Change"),
    (0x38, "LE CS Read Remote Supported Capabilities Complete v2"),
];

