//! Fixed L2CAP PSM values.
//!
//! Generated by `tools/gen_assigned_numbers.py` from the Bluetooth SIG Assigned
//! Numbers documents (<https://www.bluetooth.com/specifications/assigned-numbers/>).
//! Do not edit by hand.

/// `(PSM, name)` sorted by PSM.
pub static PSMS: &[(u16, &str)] = &[
    (0x0001, "SDP"),
    (0x0003, "RFCOMM"),
    (0x0005, "TCS-BIN"),
    (0x0007, "TCS-BIN-CORDLESS"),
    (0x000f, "BNEP"),
    (0x0011, "HID_Control"),
    (0x0013, "HID_Interrupt"),
    (0x0015, "UPnP"),
    (0x0017, "AVCTP"),
    (0x0019, "AVDTP"),
    (0x001b, "AVCTP_Browsing"),
    (0x001d, "UDI_C-Plane"),
    (0x001f, "ATT"),
    (0x0021, "3DSP"),
    (0x0023, "LE_PSM_IPSP"),
    (0x0025, "OTS"),
    (0x0027, "EATT"),
];
