#!/usr/bin/env python3
"""Generate crates/hcimon-decode/src/assigned/oui.rs from the IEEE MA-L registry.

Downloads https://standards-oui.ieee.org/oui/oui.csv (cached next to the
assigned-numbers cache) and emits a table of 24-bit OUI prefixes with the
organisation name, used to label public Bluetooth addresses.

Usage:  tools/gen_oui.py [--cache DIR] [--out FILE]
"""
import argparse
import csv
import sys
import unicodedata
import urllib.request
from pathlib import Path

URL = "https://standards-oui.ieee.org/oui/oui.csv"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cache", type=Path, default=Path(__file__).with_name("assigned_numbers_cache"))
    ap.add_argument("--out", type=Path, default=Path(__file__).resolve().parent.parent / "crates/hcimon-decode/src/assigned/oui.rs")
    args = ap.parse_args()
    path = args.cache / "oui.csv"
    if not path.exists():
        print(f"fetching {URL}", file=sys.stderr)
        args.cache.mkdir(parents=True, exist_ok=True)
        with urllib.request.urlopen(URL, timeout=120) as r:
            path.write_bytes(r.read())
    rows = {}
    with path.open(encoding="utf-8", errors="replace", newline="") as fh:
        for rec in csv.DictReader(fh):
            if rec.get("Registry") != "MA-L":
                continue
            try:
                prefix = int(rec["Assignment"], 16)
            except ValueError:
                continue
            # The registry has the odd zero-width space in a name; such format
            # characters are invisible in output and rejected by clippy.
            raw = "".join(c for c in rec["Organization Name"] if unicodedata.category(c) != "Cf")
            name = " ".join(raw.split())
            rows.setdefault(prefix, name)
    lines = [
        "//! IEEE MA-L (OUI) registry: 24-bit address prefixes and their organisations.",
        "//!",
        "//! Generated by `tools/gen_oui.py` from <https://standards-oui.ieee.org/oui/oui.csv>.",
        "//! Do not edit by hand.",
        "",
        "/// `(OUI, organisation)` sorted by OUI.",
        "pub static OUI: &[(u32, &str)] = &[",
    ]
    for prefix in sorted(rows):
        name = rows[prefix].replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    (0x{prefix:06x}, "{name}"),')
    lines.append("];")
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{len(rows)} entries", file=sys.stderr)


if __name__ == "__main__":
    main()
