#!/usr/bin/env python3
"""Generate crates/hcimon-decode/src/assigned/*.rs from the Bluetooth SIG
Assigned Numbers repository (https://bitbucket.org/bluetooth-SIG/public).

The script downloads the YAML documents it needs into a cache directory and
emits sorted static tables that the decoders look values up in.

Usage:  tools/gen_assigned_numbers.py [--cache DIR] [--out crates/hcimon-decode/src/assigned]
"""
import argparse
import re
import sys
import urllib.request
from pathlib import Path

import yaml

BASE = "https://bitbucket.org/bluetooth-SIG/public/raw/main/assigned_numbers"

UUID_FILES = [
    "uuids/declarations",
    "uuids/descriptors",
    "uuids/characteristic_uuids",
    "uuids/service_uuids",
    "uuids/service_class",
    "uuids/protocol_identifiers",
    "uuids/units",
    "uuids/object_types",
    "uuids/mesh_profile_uuids",
    "uuids/sdo_uuids",
    "uuids/member_uuids",
]
OTHER_FILES = [
    "company_identifiers/company_identifiers",
    "core/ad_types",
    "core/appearance_values",
    "core/class_of_device",
    "core/psm",
]

HEADER = """//! {what}
//!
//! Generated by `tools/gen_assigned_numbers.py` from the Bluetooth SIG Assigned
//! Numbers documents (<https://www.bluetooth.com/specifications/assigned-numbers/>).
//! Do not edit by hand.
"""


def load(cache: Path, name: str):
    path = cache / (name.replace("/", "_") + ".yaml")
    if not path.exists():
        url = f"{BASE}/{name}.yaml"
        print(f"fetching {url}", file=sys.stderr)
        cache.mkdir(parents=True, exist_ok=True)
        with urllib.request.urlopen(url, timeout=60) as r:
            path.write_bytes(r.read())
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def rs_str(s) -> str:
    s = str(s).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{s}"'


def write_table(out: Path, fname: str, what: str, ty: str, const: str, rows, doc: str, extra: str = ""):
    rows = sorted(rows, key=lambda r: r[0])
    lines = [HEADER.format(what=what)]
    lines.append(f"/// {doc}")
    lines.append(f"pub static {const}: &[({ty}, &str)] = &[")
    width = 4 if ty == "u16" else 2
    for value, name in rows:
        lines.append(f"    (0x{value:0{width}x}, {rs_str(name)}),")
    lines.append("];")
    if extra:
        lines.append("")
        lines.append(extra)
    (out / fname).write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cache", type=Path, default=Path(__file__).with_name("assigned_numbers_cache"))
    ap.add_argument("--out", type=Path, default=Path(__file__).resolve().parent.parent / "crates/hcimon-decode/src/assigned")
    args = ap.parse_args()
    out: Path = args.out
    out.mkdir(parents=True, exist_ok=True)

    # 16-bit UUIDs (all namespaces merged; first definition wins).
    uuid16 = {}
    for f in UUID_FILES:
        for e in load(args.cache, f)["uuids"]:
            uuid16.setdefault(int(e["uuid"]), e["name"])
    write_table(out, "uuid16.rs", "Names of 16-bit UUIDs (services, characteristics, descriptors, members, ...).",
                "u16", "UUID16", uuid16.items(), "`(uuid, name)` sorted by UUID.")

    companies = {int(e["value"]): e["name"] for e in load(args.cache, "company_identifiers/company_identifiers")["company_identifiers"]}
    write_table(out, "company.rs", "Company identifiers.", "u16", "COMPANIES", companies.items(),
                "`(company id, name)` sorted by id.")

    ad_types = {int(e["value"]): e["name"] for e in load(args.cache, "core/ad_types")["ad_types"]}
    write_table(out, "ad_types.rs", "Advertising / EIR data types.", "u8", "AD_TYPES", ad_types.items(),
                "`(AD type, name)` sorted by type.")

    psms = {int(e["psm"]): e["name"] for e in load(args.cache, "core/psm")["psms"]}
    write_table(out, "psm.rs", "Fixed L2CAP PSM values.", "u16", "PSMS", psms.items(), "`(PSM, name)` sorted by PSM.")

    cats = {}
    subs = {}
    for e in load(args.cache, "core/appearance_values")["appearance_values"]:
        cat = int(e["category"])
        cats[cat] = e["name"]
        for s in e.get("subcategory", []) or []:
            subs[(cat << 6) | int(s["value"])] = s["name"]
    write_table(out, "appearance.rs", "GAP appearance values.", "u16", "APPEARANCE_CATEGORIES", cats.items(),
                "`(category, name)` sorted by category (the upper 10 bits of the appearance value).")
    lines = ["", "/// `(appearance value, subcategory name)` sorted by value.",
             "pub static APPEARANCE_SUBCATEGORIES: &[(u16, &str)] = &["]
    for v in sorted(subs):
        lines.append(f"    (0x{v:04x}, {rs_str(subs[v])}),")
    lines.append("];")
    with (out / "appearance.rs").open("a", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    cod = load(args.cache, "core/class_of_device")
    services = {int(e["bit"]): e["name"] for e in cod["cod_services"]}
    majors = {}
    minors = []
    subminors = []
    minor_bits = []
    for e in cod["cod_device_class"]:
        major = int(e["major"])
        majors[major] = e["name"]
        for m in e.get("minor", []) or []:
            minors.append((major, int(m["value"]), m["name"]))
        for m in e.get("subminor", []) or []:
            subminors.append((major, int(m["value"]), m["name"]))
        for m in e.get("minor_bits", []) or []:
            minor_bits.append((major, int(m["value"]), m["name"]))
    write_table(out, "cod.rs", "Class of Device values.", "u8", "COD_SERVICES", services.items(),
                "`(bit number, major service class name)` sorted by bit.")
    lines = ["", "/// `(major device class, name)` sorted by class.", "pub static COD_MAJOR: &[(u8, &str)] = &["]
    for v in sorted(majors):
        lines.append(f"    (0x{v:02x}, {rs_str(majors[v])}),")
    lines.append("];")
    lines += ["", "/// `(major class, minor class, name)` sorted by (major, minor).",
              "pub static COD_MINOR: &[(u8, u8, &str)] = &["]
    for major, value, name in sorted(minors):
        lines.append(f"    (0x{major:02x}, 0x{value:02x}, {rs_str(name)}),")
    lines.append("];")
    lines += ["", "/// `(major class, sub-minor value, name)` for classes that split the minor field.",
              "pub static COD_SUBMINOR: &[(u8, u8, &str)] = &["]
    for major, value, name in sorted(subminors):
        lines.append(f"    (0x{major:02x}, 0x{value:02x}, {rs_str(name)}),")
    lines.append("];")
    lines += ["", "/// `(major class, minor bit, name)` for classes whose minor field is a bit mask.",
              "pub static COD_MINOR_BITS: &[(u8, u8, &str)] = &["]
    for major, value, name in sorted(minor_bits):
        lines.append(f"    (0x{major:02x}, {value}, {rs_str(name)}),")
    lines.append("];")
    with (out / "cod.rs").open("a", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    (out / "mod.rs").write_text(
        "//! Tables generated from the Bluetooth SIG Assigned Numbers documents and the IEEE OUI registry.\n"
        "//!\n"
        "//! Regenerate with `tools/gen_assigned_numbers.py` and `tools/gen_oui.py`.\n\n"
        "mod ad_types;\nmod appearance;\nmod cod;\nmod company;\nmod oui;\nmod psm;\nmod uuid16;\n\n"
        "pub use ad_types::AD_TYPES;\n"
        "pub use appearance::{APPEARANCE_CATEGORIES, APPEARANCE_SUBCATEGORIES};\n"
        "pub use cod::{COD_MAJOR, COD_MINOR, COD_MINOR_BITS, COD_SERVICES, COD_SUBMINOR};\n"
        "pub use company::COMPANIES;\n"
        "pub use oui::OUI;\n"
        "pub use psm::PSMS;\n"
        "pub use uuid16::UUID16;\n\n"
        "/// Binary search helper for the sorted `(key, name)` tables in this module.\n"
        "pub fn lookup<K: Ord + Copy>(table: &'static [(K, &'static str)], key: K) -> Option<&'static str> {\n"
        "    table\n"
        "        .binary_search_by_key(&key, |(k, _)| *k)\n"
        "        .ok()\n"
        "        .map(|i| table[i].1)\n"
        "}\n\n"
        "/// Name of a company identifier.\n"
        "pub fn company_name(id: u16) -> Option<&'static str> {\n    lookup(COMPANIES, id)\n}\n\n"
        "/// Name of a 16-bit UUID (any SIG namespace).\n"
        "pub fn uuid16_name(uuid: u16) -> Option<&'static str> {\n    lookup(UUID16, uuid)\n}\n\n"
        "/// Name of an advertising / EIR data type.\n"
        "pub fn ad_type_name(ad_type: u8) -> Option<&'static str> {\n    lookup(AD_TYPES, ad_type)\n}\n\n"
        "/// Organisation registered for the 24-bit OUI prefix of a public address (generated by `tools/gen_oui.py`).\n"
        "pub fn oui_name(prefix: u32) -> Option<&'static str> {\n    lookup(OUI, prefix)\n}\n\n"
        "/// Name of a fixed PSM.\n"
        "pub fn psm_name(psm: u16) -> Option<&'static str> {\n    lookup(PSMS, psm)\n}\n\n"
        "/// Human readable appearance, e.g. `Computer: Laptop`.\n"
        "pub fn appearance_name(value: u16) -> Option<String> {\n"
        "    let cat = lookup(APPEARANCE_CATEGORIES, value >> 6)?;\n"
        "    match lookup(APPEARANCE_SUBCATEGORIES, value) {\n"
        "        Some(sub) => Some(format!(\"{cat}: {sub}\")),\n"
        "        None if value & 0x3f == 0 => Some(cat.to_string()),\n"
        "        None => Some(format!(\"{cat}: Unknown\")),\n"
        "    }\n"
        "}\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
